### ISSUE TITLE
Feature: Async page flips with the tearing-control protocol

### ISSUE THREAD

**Issue by tadeokondrak** [mahkoh/jay#215]
In cd47baa9342a65fa47a0013bdce21616cb1b0530 the tearing-control-v1 protocol was added but the kernel didn't have support for async page flips with the atomic DRM API yet. As far as I understand this has changed and this is possible now.

**Comment by mahkoh** [comment]
Jay is currently not doing proper damage tracking. It errs on the side of damaging everything even in situations where this is not necessary (and even so, I discover with some frequency situations where we incorrectly skip damaging). This is countered by always waiting for page flip events which throttles actual rendering at the display refresh rate.

Getting VRR and async page flips to work would require first implementing airtight damage tracking.

**Comment by mahkoh** [comment]
I've looked into this a bit and the atomic API for async page flips seems hard to use:

1. No properties other than the primary plane can be changed in an async flip.
2. This includes the IN_FENCE_FD which means that we would have to do CPU waiting for rendering to complete.
3. If hardware cursors are in use, there is no way to move them. We would have to sometimes do normal commits instead of async ones to update the cursor. However, there does not seem to be a good way to figure out when the optimal point is to do this. If we get it wrong, async flips will be blocked for an entire refresh cycle.

AFAIKT, neither sway nor labwc support async flips and the wlroots API simply expects the compositor to handle these issues.

**Comment by mahkoh** [comment]
Please try #228.
